### PR TITLE
Add Travis CI

### LINKED ISSUE #9: Add Travis CI
Require that code pass a linter and that the test script passes.

### PR DESCRIPTION
**Pull request by calebeby**
Closes #9

### CODE REVIEW

**Comment by calebeby** [comment]
@howardabrams or @BrendanBurkhart Any idea how to fix the build error?

```
No matching distribution found for pyqt5-tools==5.9.0.1.2
```

**Comment by brendanburkhart** [comment]
I messed up, pyqt5-tools is Windows only. It also isn’t necessary for running the tests. I won’t have access to a computer for a while, can you remove the pyqt5-tools dependency from pipenv? That should fix it.

**Comment by calebeby** [comment]
OK, except that means that we can't use the driver station on Linux? Can we compile the `.ui` file to `.py` and start committing that and maintaining it?

**Comment by brendanburkhart** [comment]
pyqt5-tools includes a ui designer, I don’t think it’s necessary for building the driver station. We do need to find another way to install qt designer on Linux. Unless absolutely necessary I would like to keep build files uncommitted.

**Comment by calebeby** [comment]
Do we need the UI designer? Can't we make changes to the driver station by changing the code?

**Comment by brendanburkhart** [comment]
I double-checked, pyqt5 includes the pyuic utility for building the ui files. The ui designer will make it a whole lot easier, good qt code can be pretty verbose. If there isn’t a way to to get qt designer on Linux, we can think about switching to just python code.

**Comment by brendanburkhart** [comment]
Yeah, the designer is available via apt-get on Ubuntu, it should be easy to get elsewhere as well.

**Review by brendanburkhart — APPROVED** [review]

**Comment by calebeby** [comment]
OK, I got it installed

**Comment by howardabrams** [comment]
Sorry about coming into this late. Qt was originally a Linux-oriented project and there shouldn't be an issue with its portability when we run it. Also true is that it shouldn't be an issue with testing (as all tests need to run without starting any UI) ... in other words, you are on the right path. Good work!

**Comment by brendanburkhart** [comment]
@calebeby Can I merge this into master?

**Pull request merged**
